export const FETCH_MEN_PRODUCTS_REQUEST = "FETCH_MEN_PRODUCTS_REQUEST";
export const FETCH_MEN_PRODUCTS_SUCCESS = "FETCH_MEN_PRODUCTS_SUCCESS";
export const FETCH_MEN_PRODUCTS_FAILURE = "FETCH_MEN_PRODUCTS_FAILURE";
