export const FETCH_WOMEN_PRODUCTS_REQUEST = "FETCH_WOMEN_PRODUCTS_REQUEST";
export const FETCH_WOMEN_PRODUCTS_SUCCESS = "FETCH_WOMEN_PRODUCTS_SUCCESS";
export const FETCH_WOMEN_PRODUCTS_FAILURE = "FETCH_WOMEN_PRODUCTS_FAILURE";
